### ISSUE TITLE
Endzone in ParticleSystem

### ISSUE THREAD

**Issue by eugenfhtw** [psychofisch/GPGPU_examples#2]
https://github.com/psychofisch/GPGPU_examples/blob/e4a940ee7d0604a24eb2b9bd81191b639130c7a2/MiniGame/src/ParticleSystem.h#L168

Code design wise, I would remove the notion of the endzone from ParticleSystem. ParticleSystem should be as generic as possible, only responsible for creating, updating and removing particles. It does not need to know about the rules of the surrounding minigame. As an easy modification, I suggest removing the endzone member and add a generic removal method ParticleSystem::removeIntCube(const MinMaxData& cube) .

**Comment by psychofisch** [comment]
Fixed in the next commit!
