### ISSUE TITLE
fluidDamp

### ISSUE THREAD

**Issue by eugenfhtw** [psychofisch/GPGPU_examples#3]
https://github.com/psychofisch/GPGPU_examples/blob/e4a940ee7d0604a24eb2b9bd81191b639130c7a2/MiniGame/src/ParticleSystem.cpp#L725

why is fluidDamp always used as negative?

**Comment by psychofisch** [comment]
The referenced statement is shortened for  
`tmpVel[i] *= -1.0f; //the reflection part  `
`tmpVel[i] *= fluidDamp; //the dampening part`
"fluidDamp" represents an overall reflection dampening factor. "0.0" means "particles do not bounce at all", "1.0" means "particles reflect with the same speed as they hit the surface". It is only defined as a positive value to increase readability.
