### ISSUE TITLE
OCL finish()

### ISSUE THREAD

**Issue by eugenfhtw** [psychofisch/GPGPU_examples#4]
https://github.com/psychofisch/GPGPU_examples/blob/e4a940ee7d0604a24eb2b9bd81191b639130c7a2/MiniGame/src/ParticleSystem.cpp#L925

queue.finish() usually causes a slowdown and should only be used for debugging or time measurement of single method calls.

**Comment by psychofisch** [comment]
In this particular context it is used as a synchronization point, as described on the [official khronos website](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clFinish.html).
The command above the referenced code copies the "positionOutBuffer" into the "positionBuffer". This command has to finish before the next frame starts.
I will look into moving `queue.finish()` to the start of the OpenCL update function, which maybe has performance benefits.
